# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gallery

  pod 'TPKeyboardAvoiding'
  pod 'Alamofire', '~> 5.2'
  pod 'ObjectMapper'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod "TKFormTextField"

end
